version: 2

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet         # Go 官方靜態分析工具，能檢查可疑結構/錯誤用法（如 printf 參數不匹配、未使用值等）
    - errcheck      # 檢查所有返回 error 的函數調用是否正確處理（防止忽略錯誤導致 bug）
    - staticcheck   # 功能強大的靜態分析（類似 "Go 的 lint + vet 增強版"），覆蓋最佳實踐和常見錯誤
    # - unused      # (禁用) 檢查未使用的變量、函數、常量、結構字段；但有時會在開發中造成干擾
    - ineffassign # (禁用) 檢查無效的賦值（例如對變量賦值但從未使用）；通常屬於輕微問題
    - gocyclo     # (禁用) 檢查函數循環複雜度，幫助避免過於複雜的函數；但屬於風格建議
    # - predeclared # (禁用) 檢查是否使用 Go 的預聲明標識符（如 len, error）作為變量名；通常只屬於代碼風格問題
